### ISSUE TITLE
Can not import three/examples/js/postprocessing/RenderPass

### ISSUE THREAD

**Issue by benjaminb06** [wildpeaks/package-three-webpack-plugin#4]
Hello, first of all, thank you a lot for your plugin.

I use it in a project with Typescript and i can perfectly import most of the additionnal classes from three/exemples/js.

But with
```
import RenderPass from 'three/examples/js/postprocessing/RenderPass';
console.log(RenderPass);
```
Typescript compile without error but my browser throw me this error

<img width="527" alt="screen shot 2018-06-20 at 22 31 17" src="https://user-images.githubusercontent.com/8804297/41683616-6d574ed0-74db-11e8-85e5-715e9b527d8e.png">

With
```
import CopyShader from 'three/examples/js/shaders/CopyShader';
console.log(CopyShader);

```
It return undefined.

I found this plugin by your post in this issue https://github.com/mrdoob/three.js/issues/9562#issuecomment-398050320

So i saw what you advice for Typescript users, but i'm not realy a pro Typescript right now and i can't make
```
declare module 'three/examples/js/controls/OrbitControls' {
	export default THREE.OrbitControls;
}
```
for exemple, without compile errors.

Maybe there is a link ? Do i need to fix Typescript intellisence to solve the problem ?
Is it normal my browser throw this error even if i import it without module declaration, just like a classic ES6 import ?
Maybe i'm doing something wrong, or maybe is there any particular classes in three/exemples/js ?

Thank you in advance for your answers :)

**Comment by cecilemuller** [comment]
Thanks for using the plugin 😃 

You stumbled on something odd: the issue with RenderPass is happening because it relies on `THREE.Pass` which appears to be missing from package `three`:

	import {Pass} from 'three';
	console.log(Pass); // undefined

I'll look into why it's missing.


As for CopyShader, it imports fine on its own / the declare module is not required, but I'll post an example later.

**Comment by cecilemuller** [comment]
Found it: `THREE.Pass` is defined by `examples/js/postprocessing/EffectComposer.js`, so I'll modify the plugin to add a special rule for it.

**Comment by cecilemuller** [comment]
[Version 2.0.0](https://github.com/wildpeaks/package-three-webpack-plugin/releases/tag/v2.0.0) should solve the issue: I ended up modifying a lot of the core instead of merely adding a special rule for it, to keep things consistent 😃 

I'll post an example application using it and link it here later.

**Comment by cecilemuller** [comment]
Here's an example using `RenderPass`:
https://github.com/wildpeaks/threejs-typescript-examples/blob/master/src/webgl_postprocessing.ts

As for the "declare module" blocks, the simplest is to put them in a `global.d.ts` file at the root of your project, like this:
https://github.com/wildpeaks/threejs-typescript-examples/blob/master/globals.d.ts

**Comment by benjaminb06** [comment]
Hello,

Thank you a lot for your reactivity, and sorry for mine, i was sick last week !

I checked and now i have another problem.

<img width="852" alt="screen shot 2018-06-25 at 19 48 08" src="https://user-images.githubusercontent.com/8804297/41872608-aedd5a26-78c2-11e8-91c1-32023dd09667.png">

Here is my code
```
import * as THREE from "three";
import {EffectComposer} from 'three/examples/js/postprocessing/EffectComposer';
import {CopyShader} from 'three/examples/js/shaders/CopyShader';
import {RenderPass} from 'three/examples/js/postprocessing/RenderPass';
import {ShaderPass} from 'three/examples/js/postprocessing/ShaderPass';
```
I tested with your exemple here https://github.com/wildpeaks/threejs-typescript-examples/blob/master/src/webgl_postprocessing.ts and i got a similar error about the CopyShader. But in your code i just needed to import the CopyShader to fix it, i don't know why it's not the same behavior with mine.

I think is a problem like classes are imported as module but are not linked with THREE which is a module too with Typescript, am i wrong ? 

I also tried to import only what i need in THREE like you with
`import {WebGLRenderer, PerspectiveCamera, Scene, Fog, Object3D, SphereBufferGeometry, MeshPhongMaterial, Mesh, AmbientLight, DirectionalLight} from 'three'; `
with the intention to not put something wrong under the THREE name, but it changed nothing.

Thank you too for the exemple about Typescript, it solve the intellisence bug.

Sorry if my problem is stupid, I have this feeling but I haven't fix it yet.

**Comment by cecilemuller** [comment]
No worries 😃

If you download [this example repository](https://github.com/wildpeaks/threejs-typescript-examples), then run `npm install` (to install dependencies), then run `npm run watch` (to launch the DevServer), then open `http://localhost:8000/webgl_postprocessing.html` in your browser, does the page work ?

If so, then please compare what's different between the working example and your setup because unfortunately I cannot reproduce the error.

The first thing I'd recommend is comparing [tsconfig.json](https://github.com/wildpeaks/threejs-typescript-examples/blob/master/tsconfig.json).


Unrelated to this issue, I will soon post a new version plugin because I've [located more files](https://github.com/wildpeaks/package-three-webpack-plugin/issues/11) that export more than one class and/or don't create their class in the THREE namespace (so I'm really glad I went with named exports instead of a special rule for EffectComposer :) ).

**Comment by cecilemuller** [comment]
Better wait for the update before making further tests because it modifies the internal imports & exports of quite a few files.

Already managed to automate detecting multiple and "other then THREE namespace" exports  (despite it used like 7 different ways of structuring example files) and I was hoping to work on the rest I want to do for the update this week-end, but unfortunately my main two customers happened to both need urgent things for next week out of the blue, so I have to delay the update a bit.
