### ISSUE TITLE
Use the raw loader?

### ISSUE THREAD

**Issue by te-chris** [wildpeaks/package-three-webpack-plugin#45]

**Comment by te-chris** [comment]
Apologies, got trigger happy and submitted before I had a chance to write anything.

Is there a way to use the raw loader inline? We have a slightly modified version of `OrbitControl` which we'd like to use in an ES2015 project and trying to require like so: `import { OrbitControls } from '@wildpeaks/three-webpack-plugin!babel-loader!./OrbitControls';` only loaded the plugin.

**Comment by cecilemuller** [comment]
No worries 😃 

However if you have a modified version of OrbitControls, it would be better if you wrote it directly as Es Module instead of adding something in this plugin as it's only meant to be a temporary fix until three.js itself provides es modules versions of the files, otherwise it would be too complex to maintain.

Sorry I can't write a longer reply because I'm still very swamped with customers projects at the moment.
